<?php




?>

<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Exercice Hash</title>
	</head>
	<body>
	    <form method="POST" action="decrypt_password.php">
	        <input type="password" name="password" id="password" placeholder="password"/>
	        <input type="password" name="passwordSecure" id="passwordSecure" placeholder="passwordSecure"/>
	        <input type="submit" value="Submit"/>
	    </form>
	</body>
</html>