<?php
    if (isset($_SESSION["user"], $_SESSION["user"]["first_name"], $_SESSION["user"]["last_name"] )) {
        echo "<h1>Bonjour" . " " . $_SESSION["user"]["first_name"] . " " . $_SESSION["user"]["last_name"] . "</h1>";
    }
?>


<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Home exercice auth</title>
	</head>
	<body>
        <nav>
            <ul>
                <li>
                    <a href="index.php?route=inscription">Inscription</a>
                </li>
                <li>
                    <a href="index.php?route=connexion">Connexion</a>
                </li>
            </ul>
        </nav>
    </body>
</html>