<form method="POST" action="logic/register.php">
    <input type="text" name="first_name" id="first_name" placeholder="first_name"/>
    <input type="text" name="last_name" id="last_name" placeholder="last_name"/>
    <input type="mail" name="email" id="email" placeholder="email"/>
    <input type="password" name="password" id="password" placeholder="password"/>
    <input type="submit" value="Submit"/>
</form>